basic_bundles:

  StofDoctrineExtensionBundle:
    package_name: "stof/doctrine-extensions-bundle"
    version: "1.1.*@dev"

  FOSUserBundle:
    package_name: "friendsofsymfony/user-bundle"
    version: "2.0.*@dev"

  BreadcrumbsBundle:
    package_name: "whiteoctober/breadcrumbs-bundle"
    version: "1.0.0"

  KnpPaginatorBundle:
    package_name: "knplabs/knp-paginator-bundle"
    version: "2.4.*@dev"

  JMSSerializerBundle:
    package_name: "jms/serializer-bundle"
    version: "0.13.*@dev"

  VichUploaderBundle:
    package_name: "vich/uploader-bundle"
    version: "0.9.0"

  AvalancheImagineBundle:
    package_name: "avalanche123/imagine-bundle"
    version: "2.1.2"

  lessphp:
    package_name: "leafo/lessphp"
    version: "0.4.*@dev"